### ISSUE TITLE
Introduce guideline style for toc

### ISSUE THREAD

**Issue by legoming** [MacDownApp/macdown#1075]
TOC is a great feature for markdown, the only issue for me is it's not so convenient if it located on top.

I created TOC twice in my local build
- one used as TOC on top (so I can reserve TOC on pdf)
- one used as guideline show on right side (with fixed position, but will be hidden in pdf/print) (so I can easily jump to any section from anywhere)

<img src="https://raw.githubusercontent.com/legoming/macdown/master/assets/toc%20vs%20guideline.png" style="width:300px">

While I know nothing about Objective C, I implemented it in an ugly way -- just copy the code from toc, [4975fd7](https://github.com/legoming/macdown/commit/4975fd7d95d4c9db69310e5273d096249d5fd847).
Just want to know if someone else like a feature like this, and introduce it in formal.

**Comment by FranklinYu** [comment]
I don’t get it; why do you need two ToC? You can have guideline-only in web view, and normal ToC in PDF. Just use some CSS trick.

**Comment by legoming** [comment]
I have tried, but doesn’t work
I show toc as guideline in html and move it back to normal position when printing, but the toc will overlap with content in pdf.
I don’t know how to fix it :(

**Comment by FranklinYu** [comment]
> the toc will overlap with content in pdf.

How did you modified the style? It shouldn’t be the case.

**Comment by legoming** [comment]
I don't remember exactly, just do sth like:

**define toc with guideline style**

```css
ul.toc {
  list-style-type: none;
  font-family: Roboto, "Noto Serif SC";
  color: #134e8e;
  background-color: #f0f0f0;
  //margin-left: -28px;
  float: right;
  position: fixed;
  top: 30px;
  right: 130px;
  z-index: -999;
  width: 210px;
  //height: 87%;
  max-width: 210px;
  max-height: 87%;
  overflow:auto;
  opacity: 0.8;
  border-left: 1px solid #f0f0f0;
  border-radius: 3px;
  padding: 10px;
  padding-top: 30px;
  padding-bottom: 30px;
  //display: -webkit-flex; /* Safari */
  -webkit-flex-wrap: wrap; /* Safari 6.1+ */
  //display: flex;   
  flex-wrap: wrap;
  white-space: nowrap;
}

/*ul.toc:before {
  content: "Table of Content\00000A\00000A";
  white-space: pre;
  font-weight: bold;
}*/

ul.toc li {
  list-style-type: none;
  /*margin-top: -20px;*/
  padding-left: -10px;
  line-height: 25px;
}

ul.toc li:first-child {
  margin-top: -15px;
}

ul.toc li:last-child {
  margin-bottom: -15px;
}
```

**refine toc as normal style in print**

```css
@media print {
  ul.toc {
    // refine as normal style
  }
}
```
