### ISSUE TITLE
Configurable page margin for pdf export

### ISSUE THREAD

**Issue by gotschmarcel** [MacDownApp/macdown#196]
It's really bugging me that the page margin is so small. It would be better if there were a way to configure the margin. The documents readability improves with a better margin.

e.g.
![7176430](https://cloud.githubusercontent.com/assets/4235955/4715098/f9f1d10e-58fa-11e4-9f41-fbfcd7bcc3bf.png)

**Comment by hugozaragoza** [comment]
still waiting for some way to give margins to the PDF :)

**Comment by webforwes** [comment]
Did this ever get added or resolved? Huge top margins and too-tight side margins on PDF exports with no real way set them.

**Comment by waterlink** [comment]
@webforwes Did you try to use css to set these margins? Something like:

```css
/* pdf.css */

@page {
  margin: 2cm 2cm;   /* play with these two to set it to your liking */
}
```

And to include that css just put this html tag at the top of your macdown file:

```markdown
<link href="pdf.css" rel="stylesheet">
```

**Comment by utdrmac** [comment]
Doesn't look like this has been solved. I've been editing the included CSS styles to no avail on getting better control over PDF export. How come the PDF export just doesn't simply follow CSS rules?

**Comment by jansensan** [comment]
I have been able to change the margins with a `*.css` file, however I had to use inches as a unit of measurement:

```css
@media print {
  body {
    margin: 1in;
  }
}
```
