### ISSUE TITLE
some css  does not work when export as PDF

### ISSUE THREAD

**Issue by hufan-Akari** [MacDownApp/macdown#520]
How to control the pdf style with css?
I find the code behind in the github2.css
```css
@media print {
  table, pre {
		page-break-inside: avoid;
	}
  pre {
		word-wrap: break-word;
	}
}
```

when i try to modify it like this:

```css
@media print {
  table, pre {
		page-break-inside: avoid;
	}
  pre {
		word-wrap: break-word;
	}
  h1 {page-break-before: always;}
}
```
there should be a page break before every h1 element.
But it doesn't work,
unless I export it as html and convert to PDF.

But there is something different between the two method .

I prefer the direct exported pdf file .
Its margin is perfect .
is there default style on pdf file?
