### ISSUE TITLE
[Feature] Scroll past end

### ISSUE THREAD

**Issue by schickling** [MacDownApp/macdown#60]
I think it would be convenient if one would be able to scroll past the end of a page. I current always end up adding line breaks at the end of a document in order to not crawl on the last line.

Sublime Text for example also has this feature: http://sublimetext.userecho.com/topic/101697-ability-to-over-scroll/

**Comment by seriypshick** [comment]
I feel like it scrolls too far. I added the code below to my theme to adjust it to my liking
```css
.CodeMirror-lines { padding-bottom: 400px!important };
```
