### ISSUE TITLE
Modify colour on standard CSS PDF output

### ISSUE THREAD

**Issue by jckw** [MacDownApp/macdown#949]
This is a super small issue about the PDF output for the standard themes on dark backgrounds. 

For some reason there is a style in a couple of the themes that changes the text colour to black for printing: 
```css
@media print {
        ...
	body,code,pre code,h1,h2,h3,h4,h5,h6 {
		color: black;
	}
        ...
}
```

This isn't really necessary or useful for 2 reasons:
1. You don't get a PDF/ print output consistent with what your preview shows you. 
2. The output on dark backgrounds (e.g. Clearness Dark.css) is unreadable. 

It would probably be easiest if this style is simply removed.
